export const API_URL = "http://127.0.0.1:8000";

export const colors = [
  "red",
  "green",
  "black",
  "pink",
  "yellow",
  "gray",
  "brown",
  "blue",
];

export const blockedMsDelay = 10000;

export const mockSummary = [
  {
    questionText:
      "Пожалуйста, оцените самолет, на котором Вы летите с AMONIC Airlines",
    answers: [
      {
        text: "Великолепно",
        total: 21,
        gender: {
          M: 21,
          F: 0,
        },
        age: {
          "18-24": 21,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 4,
          CAI: 6,
          BAH: 8,
          ADE: 0,
          DOH: 2,
          RUH: 1,
          Economy: 16,
          Business: 2,
          "First Class": 3,
        },
      },
      {
        text: "Очень хорошо",
        total: 11,
        gender: {
          M: 11,
          F: 0,
        },
        age: {
          "18-24": 11,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 4,
          CAI: 1,
          BAH: 5,
          ADE: 0,
          DOH: 1,
          RUH: 0,
          Economy: 9,
          Business: 0,
          "First Class": 2,
        },
      },
      {
        text: "Хорошо",
        total: 22,
        gender: {
          M: 22,
          F: 0,
        },
        age: {
          "18-24": 22,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 4,
          CAI: 7,
          BAH: 10,
          ADE: 0,
          DOH: 1,
          RUH: 0,
          Economy: 18,
          Business: 2,
          "First Class": 2,
        },
      },
      {
        text: "Нормально",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 0,
          BAH: 3,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 3,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Необходимо улучшить",
        total: 5,
        gender: {
          M: 5,
          F: 0,
        },
        age: {
          "18-24": 5,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 2,
          CAI: 0,
          BAH: 1,
          ADE: 0,
          DOH: 0,
          RUH: 2,
          Economy: 4,
          Business: 0,
          "First Class": 1,
        },
      },
      {
        text: "Плохо",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 2,
          BAH: 1,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 3,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Не знаю",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 1,
          CAI: 1,
          BAH: 0,
          ADE: 0,
          DOH: 0,
          RUH: 1,
          Economy: 3,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Ответа нет",
        total: 4,
        gender: {
          M: 4,
          F: 0,
        },
        age: {
          "18-24": 4,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 2,
          CAI: 1,
          BAH: 0,
          ADE: 0,
          DOH: 0,
          RUH: 1,
          Economy: 4,
          Business: 0,
          "First Class": 0,
        },
      },
    ],
  },
  {
    questionText: "Как бы Вы оценили наших борт проводников",
    answers: [
      {
        text: "Великолепно",
        total: 9,
        gender: {
          M: 9,
          F: 0,
        },
        age: {
          "18-24": 9,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 4,
          BAH: 5,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 8,
          Business: 0,
          "First Class": 1,
        },
      },
      {
        text: "Очень хорошо",
        total: 20,
        gender: {
          M: 20,
          F: 0,
        },
        age: {
          "18-24": 20,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 5,
          CAI: 4,
          BAH: 9,
          ADE: 0,
          DOH: 1,
          RUH: 1,
          Economy: 17,
          Business: 1,
          "First Class": 2,
        },
      },
      {
        text: "Хорошо",
        total: 11,
        gender: {
          M: 11,
          F: 0,
        },
        age: {
          "18-24": 11,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 2,
          CAI: 3,
          BAH: 4,
          ADE: 0,
          DOH: 1,
          RUH: 1,
          Economy: 10,
          Business: 0,
          "First Class": 1,
        },
      },
      {
        text: "Нормально",
        total: 15,
        gender: {
          M: 15,
          F: 0,
        },
        age: {
          "18-24": 15,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 4,
          CAI: 2,
          BAH: 6,
          ADE: 0,
          DOH: 1,
          RUH: 2,
          Economy: 12,
          Business: 3,
          "First Class": 0,
        },
      },
      {
        text: "Необходимо улучшить",
        total: 4,
        gender: {
          M: 4,
          F: 0,
        },
        age: {
          "18-24": 4,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 2,
          BAH: 2,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 2,
          Business: 0,
          "First Class": 2,
        },
      },
      {
        text: "Плохо",
        total: 0,
        gender: {
          M: 0,
          F: 0,
        },
        age: {
          "18-24": 0,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 0,
          BAH: 0,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 0,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Не знаю",
        total: 10,
        gender: {
          M: 10,
          F: 0,
        },
        age: {
          "18-24": 10,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 5,
          CAI: 2,
          BAH: 1,
          ADE: 0,
          DOH: 1,
          RUH: 1,
          Economy: 8,
          Business: 0,
          "First Class": 2,
        },
      },
      {
        text: "Ответа нет",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 1,
          CAI: 1,
          BAH: 1,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 3,
          Business: 0,
          "First Class": 0,
        },
      },
    ],
  },
  {
    questionText: "Как бы Вы оценили развлечения во время полета",
    answers: [
      {
        text: "Великолепно",
        total: 16,
        gender: {
          M: 16,
          F: 0,
        },
        age: {
          "18-24": 16,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 2,
          CAI: 6,
          BAH: 4,
          ADE: 0,
          DOH: 1,
          RUH: 3,
          Economy: 13,
          Business: 0,
          "First Class": 3,
        },
      },
      {
        text: "Очень хорошо",
        total: 19,
        gender: {
          M: 19,
          F: 0,
        },
        age: {
          "18-24": 19,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 6,
          CAI: 4,
          BAH: 6,
          ADE: 0,
          DOH: 1,
          RUH: 2,
          Economy: 16,
          Business: 2,
          "First Class": 1,
        },
      },
      {
        text: "Хорошо",
        total: 2,
        gender: {
          M: 2,
          F: 0,
        },
        age: {
          "18-24": 2,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 1,
          BAH: 1,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 2,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Нормально",
        total: 16,
        gender: {
          M: 16,
          F: 0,
        },
        age: {
          "18-24": 16,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 6,
          CAI: 2,
          BAH: 8,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 13,
          Business: 1,
          "First Class": 2,
        },
      },
      {
        text: "Необходимо улучшить",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 1,
          BAH: 2,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 3,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Плохо",
        total: 10,
        gender: {
          M: 10,
          F: 0,
        },
        age: {
          "18-24": 10,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 1,
          CAI: 2,
          BAH: 5,
          ADE: 0,
          DOH: 2,
          RUH: 0,
          Economy: 9,
          Business: 1,
          "First Class": 0,
        },
      },
      {
        text: "Не знаю",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 1,
          CAI: 1,
          BAH: 1,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 2,
          Business: 0,
          "First Class": 1,
        },
      },
      {
        text: "Ответа нет",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 1,
          CAI: 1,
          BAH: 1,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 2,
          Business: 0,
          "First Class": 1,
        },
      },
    ],
  },
  {
    questionText: "Пожалуйста, оцените цену на билет Вашего маршрута",
    answers: [
      {
        text: "Великолепно",
        total: 11,
        gender: {
          M: 11,
          F: 0,
        },
        age: {
          "18-24": 11,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 4,
          CAI: 4,
          BAH: 3,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 7,
          Business: 1,
          "First Class": 3,
        },
      },
      {
        text: "Очень хорошо",
        total: 14,
        gender: {
          M: 14,
          F: 0,
        },
        age: {
          "18-24": 14,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 1,
          CAI: 3,
          BAH: 6,
          ADE: 0,
          DOH: 2,
          RUH: 2,
          Economy: 12,
          Business: 0,
          "First Class": 2,
        },
      },
      {
        text: "Хорошо",
        total: 30,
        gender: {
          M: 30,
          F: 0,
        },
        age: {
          "18-24": 30,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 7,
          CAI: 7,
          BAH: 15,
          ADE: 0,
          DOH: 0,
          RUH: 1,
          Economy: 27,
          Business: 2,
          "First Class": 1,
        },
      },
      {
        text: "Нормально",
        total: 0,
        gender: {
          M: 0,
          F: 0,
        },
        age: {
          "18-24": 0,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 0,
          BAH: 0,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 0,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Необходимо улучшить",
        total: 3,
        gender: {
          M: 3,
          F: 0,
        },
        age: {
          "18-24": 3,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 0,
          CAI: 1,
          BAH: 1,
          ADE: 0,
          DOH: 0,
          RUH: 1,
          Economy: 2,
          Business: 0,
          "First Class": 1,
        },
      },
      {
        text: "Плохо",
        total: 1,
        gender: {
          M: 1,
          F: 0,
        },
        age: {
          "18-24": 1,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 1,
          CAI: 0,
          BAH: 0,
          ADE: 0,
          DOH: 0,
          RUH: 0,
          Economy: 1,
          Business: 0,
          "First Class": 0,
        },
      },
      {
        text: "Не знаю",
        total: 8,
        gender: {
          M: 8,
          F: 0,
        },
        age: {
          "18-24": 8,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 2,
          CAI: 3,
          BAH: 1,
          ADE: 0,
          DOH: 2,
          RUH: 0,
          Economy: 6,
          Business: 1,
          "First Class": 1,
        },
      },
      {
        text: "Ответа нет",
        total: 5,
        gender: {
          M: 5,
          F: 0,
        },
        age: {
          "18-24": 5,
          "25-39": 0,
          "40-59": 0,
          "60+": 0,
        },
        airport: {
          AUH: 2,
          CAI: 0,
          BAH: 2,
          ADE: 0,
          DOH: 0,
          RUH: 1,
          Economy: 5,
          Business: 0,
          "First Class": 0,
        },
      },
    ],
  },
];
